#!/bin/bash
mysql_password=$(perl -mNethServer::Password -e "print NethServer::Password::store('mysql')")

# Functions

function fbx_query {
    mysql -uroot -p$mysql_password asterisk -B --silent -e "$1"
}


# Create rest module sql tables
for i in $(ls /var/www/html/freepbx/contatta/sql/*.sql); do
    mysql -uroot -p$mysql_password asterisk < ${i}
done

# Install FreePBX module
modules_dir='/var/www/html/freepbx/admin/modules/'
m='/usr/src/contatta/modules/contatta.tar.gz'
filename=$(basename "$m")
name="${filename%.tar.gz}"

if [ ! -d $modules_dir$name ]; then
    mkdir -p $modules_dir$name
else
    rm -fr $modules_dir$name/*
fi
tar xf $m -C $modules_dir$name --strip-components 1
chown -R asterisk:asterisk $modules_dir$name

# Enable the mini-HTTP Server and TLS for the mini-HTTP Server
fbx_query 'UPDATE `freepbx_settings` SET `value` = "1" WHERE keyword = "HTTPENABLED"'
fbx_query 'UPDATE `freepbx_settings` SET `value` = "1" WHERE keyword = "HTTPTLSENABLE"'
# Set NethServer certificate as default
fbx_query 'UPDATE `freepbx_settings` SET `value` = "/etc/asterisk/keys/NethServer.pem" WHERE keyword = "HTTPTLSCERTFILE"'
fbx_query 'UPDATE `freepbx_settings` SET `value` = "/etc/asterisk/keys/NethServer.key" WHERE keyword = "HTTPTLSPRIVATEKEY"'

# Install other needed modules
for MODULE in certman manager queues ringgroups; do
    if [[ ! $(scl enable rh-php56 -- fwconsole ma list | awk '{print $2,$6}' | grep -q $MODULE) ]] ; then
        scl enable rh-php56 -- fwconsole ma downloadinstall $MODULE &> /dev/null
    fi
done

# install contatta module
/usr/bin/scl enable rh-php56 '/usr/sbin/fwconsole moduleadmin install contatta'

# Apply changes
/usr/bin/scl enable rh-php56 -- fwconsole r

# install lame if not installed
if ! rpm -qa | grep lame; then
    yum install lame
fi
